### ISSUE TITLE
Abstract usage of hydra through whisper

### ISSUE THREAD

**Issue by claudiosegala** [labbsr0x/whisper-client#10]
I think it would be nice to abstract the usage of hydra through whisper for the users of whisper-client. This means whisper absorbing most of the whisper-client code and make whisper redirect to hydra.

This way it would be less code on the client and the users of whisper would have an easier setup.

**Comment by eabili0** [comment]
That would be a very welcomed improvement! Thanks @claudiosegala

**Comment by eabili0** [comment]
We should open an API at whisper to recover hydra's urls. That way the abstraction is a little less dramatic.
