### ISSUE TITLE
Introspect token api is expecting a space separated Scope list

### ISSUE THREAD

**Issue by GabrielDev** [labbsr0x/whisper-client#24]
The wrong behavior has been identified at the following line, where the scopes are being url encoded:

https://github.com/labbsr0x/whisper-client/blob/1c65f6ca9e5276d290006bf57969015255e4bed9/client/client.go#L124

Cheers!

**Comment by eabili0** [comment]
Thanks @GabrielDev, will look into it right now!

**Comment by eabili0** [comment]
Not a bug.
