### ISSUE TITLE
Add mux middleware

### ISSUE THREAD

**Issue by eabili0** [labbsr0x/whisper-client#5]

**Comment by claudiosegala** [comment]
@abilioesteves isn't it already implemented in:
https://github.com/labbsr0x/whisper-client/blob/faaa25fe15dde36f7c8cbb9f60cb87752211dc60/client/client.go#L87-L107

If this is not what you are referring to by 'Add mux middleware', could you elaborate?

**Comment by eabili0** [comment]
Yeah. I'll close this issue.
